[package]
name = "hermit"
version = "0.0.2"
authors = [
	"Stefan Lankes <slankes@eonerc.rwth-aachen.de>",
	"Colin Finck <colin.finck@rwth-aachen.de>"
]
build = "build.rs"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["no-std"]
description = """
A Rust-based, lightweight unikernel
"""

[lib]
name = "hermit"
#crate-type = ["staticlib"]

[features]
#default = ["vga"]
default = []
vga = []
#rustc-dep-of-std = []
rustc-dep-of-std = ['core', 'alloc', 'compiler_builtins/rustc-dep-of-std', 'compiler_builtins/mem']

[dependencies]
bitflags = { path = "./crates/bitflags", features = ['rustc-dep-of-std'] }
core = { path = "../libcore", optional = true }
alloc = { path = "../liballoc", optional = true }
spin = { path = './crates/spin-rs', features = ['rustc-dep-of-std'] }
compiler_builtins = { version = "0.1", optional = true, features = ['rustc-dep-of-std', 'mem'] }
#lazy_static = { path = './crates/lazy-static', features = ['spin_no_std', 'rustc-dep-of-std'] }

#[dependencies.smoltcp]
#git = "https://github.com/hermitcore/smoltcp.git"
#default-features = false
#features = ["log", "socket-tcp", "socket-raw", "socket-udp", "proto-dhcpv4", "proto-ipv6", "proto-ipv4"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
hermit-multiboot = { path = './crates/multiboot', features = ['rustc-dep-of-std'] }
x86 = { path = './crates/rust-x86', default-features = false, features = ['rustc-dep-of-std'] }
